# CMake generated Testfile for 
# Source directory: /users/kanwu/external_btree/cmake-3.11.1/Tests/CMakeOnly
# Build directory: /users/kanwu/external_btree/cmake-3.11.1/Tests/CMakeOnly
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(CMakeOnly.LinkInterfaceLoop "/users/kanwu/external_btree/cmake-3.11.1/bin/cmake" "-DTEST=LinkInterfaceLoop" "-P" "/users/kanwu/external_btree/cmake-3.11.1/Tests/CMakeOnly/Test.cmake")
set_tests_properties(CMakeOnly.LinkInterfaceLoop PROPERTIES  TIMEOUT "90")
add_test(CMakeOnly.CheckSymbolExists "/users/kanwu/external_btree/cmake-3.11.1/bin/cmake" "-DTEST=CheckSymbolExists" "-P" "/users/kanwu/external_btree/cmake-3.11.1/Tests/CMakeOnly/Test.cmake")
add_test(CMakeOnly.CheckCXXSymbolExists "/users/kanwu/external_btree/cmake-3.11.1/bin/cmake" "-DTEST=CheckCXXSymbolExists" "-P" "/users/kanwu/external_btree/cmake-3.11.1/Tests/CMakeOnly/Test.cmake")
add_test(CMakeOnly.CheckCXXCompilerFlag "/users/kanwu/external_btree/cmake-3.11.1/bin/cmake" "-DTEST=CheckCXXCompilerFlag" "-P" "/users/kanwu/external_btree/cmake-3.11.1/Tests/CMakeOnly/Test.cmake")
add_test(CMakeOnly.CheckLanguage "/users/kanwu/external_btree/cmake-3.11.1/bin/cmake" "-DTEST=CheckLanguage" "-P" "/users/kanwu/external_btree/cmake-3.11.1/Tests/CMakeOnly/Test.cmake")
add_test(CMakeOnly.CheckStructHasMember "/users/kanwu/external_btree/cmake-3.11.1/bin/cmake" "-DTEST=CheckStructHasMember" "-P" "/users/kanwu/external_btree/cmake-3.11.1/Tests/CMakeOnly/Test.cmake")
add_test(CMakeOnly.CompilerIdC "/users/kanwu/external_btree/cmake-3.11.1/bin/cmake" "-DTEST=CompilerIdC" "-P" "/users/kanwu/external_btree/cmake-3.11.1/Tests/CMakeOnly/Test.cmake")
add_test(CMakeOnly.CompilerIdCXX "/users/kanwu/external_btree/cmake-3.11.1/bin/cmake" "-DTEST=CompilerIdCXX" "-P" "/users/kanwu/external_btree/cmake-3.11.1/Tests/CMakeOnly/Test.cmake")
add_test(CMakeOnly.AllFindModules "/users/kanwu/external_btree/cmake-3.11.1/bin/cmake" "-DTEST=AllFindModules" "-DCMAKE_ARGS=-DCMake_TEST_CMakeOnly.AllFindModules_NO_VERSION=" "-P" "/users/kanwu/external_btree/cmake-3.11.1/Tests/CMakeOnly/Test.cmake")
add_test(CMakeOnly.SelectLibraryConfigurations "/users/kanwu/external_btree/cmake-3.11.1/bin/cmake" "-DTEST=SelectLibraryConfigurations" "-P" "/users/kanwu/external_btree/cmake-3.11.1/Tests/CMakeOnly/Test.cmake")
add_test(CMakeOnly.TargetScope "/users/kanwu/external_btree/cmake-3.11.1/bin/cmake" "-DTEST=TargetScope" "-P" "/users/kanwu/external_btree/cmake-3.11.1/Tests/CMakeOnly/Test.cmake")
add_test(CMakeOnly.find_library "/users/kanwu/external_btree/cmake-3.11.1/bin/cmake" "-DTEST=find_library" "-P" "/users/kanwu/external_btree/cmake-3.11.1/Tests/CMakeOnly/Test.cmake")
add_test(CMakeOnly.find_path "/users/kanwu/external_btree/cmake-3.11.1/bin/cmake" "-DTEST=find_path" "-P" "/users/kanwu/external_btree/cmake-3.11.1/Tests/CMakeOnly/Test.cmake")
add_test(CMakeOnly.ProjectInclude "/users/kanwu/external_btree/cmake-3.11.1/bin/cmake" "-DTEST=ProjectInclude" "-DCMAKE_ARGS=-DCMAKE_PROJECT_ProjectInclude_INCLUDE=/users/kanwu/external_btree/cmake-3.11.1/Tests/CMakeOnly/ProjectInclude/include.cmake" "-P" "/users/kanwu/external_btree/cmake-3.11.1/Tests/CMakeOnly/Test.cmake")
add_test(CMakeOnly.MajorVersionSelection-PythonLibs_2 "/users/kanwu/external_btree/cmake-3.11.1/bin/cmake" "-DTEST=MajorVersionSelection-PythonLibs_2" "-DTEST_SOURCE=MajorVersionSelection" "-DCMAKE_ARGS=-DMAJOR_TEST_MODULE=PythonLibs;-DMAJOR_TEST_VERSION=2;-DMAJOR_TEST_NO_LANGUAGES=FALSE;-DMAJOR_TEST_VERSION_VAR=PYTHONLIBS_VERSION_STRING" "-P" "/users/kanwu/external_btree/cmake-3.11.1/Tests/CMakeOnly/Test.cmake")
add_test(CMakeOnly.MajorVersionSelection-PythonLibs_3 "/users/kanwu/external_btree/cmake-3.11.1/bin/cmake" "-DTEST=MajorVersionSelection-PythonLibs_3" "-DTEST_SOURCE=MajorVersionSelection" "-DCMAKE_ARGS=-DMAJOR_TEST_MODULE=PythonLibs;-DMAJOR_TEST_VERSION=3;-DMAJOR_TEST_NO_LANGUAGES=FALSE;-DMAJOR_TEST_VERSION_VAR=PYTHONLIBS_VERSION_STRING" "-P" "/users/kanwu/external_btree/cmake-3.11.1/Tests/CMakeOnly/Test.cmake")
add_test(CMakeOnly.MajorVersionSelection-PythonInterp_2 "/users/kanwu/external_btree/cmake-3.11.1/bin/cmake" "-DTEST=MajorVersionSelection-PythonInterp_2" "-DTEST_SOURCE=MajorVersionSelection" "-DCMAKE_ARGS=-DMAJOR_TEST_MODULE=PythonInterp;-DMAJOR_TEST_VERSION=2;-DMAJOR_TEST_NO_LANGUAGES=TRUE;-DMAJOR_TEST_VERSION_VAR=PYTHON_VERSION_STRING" "-P" "/users/kanwu/external_btree/cmake-3.11.1/Tests/CMakeOnly/Test.cmake")
add_test(CMakeOnly.MajorVersionSelection-PythonInterp_3 "/users/kanwu/external_btree/cmake-3.11.1/bin/cmake" "-DTEST=MajorVersionSelection-PythonInterp_3" "-DTEST_SOURCE=MajorVersionSelection" "-DCMAKE_ARGS=-DMAJOR_TEST_MODULE=PythonInterp;-DMAJOR_TEST_VERSION=3;-DMAJOR_TEST_NO_LANGUAGES=TRUE;-DMAJOR_TEST_VERSION_VAR=PYTHON_VERSION_STRING" "-P" "/users/kanwu/external_btree/cmake-3.11.1/Tests/CMakeOnly/Test.cmake")
add_test(CMakeOnly.MajorVersionSelection-Qt_3 "/users/kanwu/external_btree/cmake-3.11.1/bin/cmake" "-DTEST=MajorVersionSelection-Qt_3" "-DTEST_SOURCE=MajorVersionSelection" "-DCMAKE_ARGS=-DMAJOR_TEST_MODULE=Qt;-DMAJOR_TEST_VERSION=3;-DMAJOR_TEST_NO_LANGUAGES=FALSE;-DMAJOR_TEST_VERSION_VAR=QT_VERSION_STRING" "-P" "/users/kanwu/external_btree/cmake-3.11.1/Tests/CMakeOnly/Test.cmake")
add_test(CMakeOnly.MajorVersionSelection-Qt_4 "/users/kanwu/external_btree/cmake-3.11.1/bin/cmake" "-DTEST=MajorVersionSelection-Qt_4" "-DTEST_SOURCE=MajorVersionSelection" "-DCMAKE_ARGS=-DMAJOR_TEST_MODULE=Qt;-DMAJOR_TEST_VERSION=4;-DMAJOR_TEST_NO_LANGUAGES=FALSE;-DMAJOR_TEST_VERSION_VAR=QT_VERSION_STRING" "-P" "/users/kanwu/external_btree/cmake-3.11.1/Tests/CMakeOnly/Test.cmake")
